#ifndef ERRORDEFINES_HPP_
#define ERRORDEFINES_HPP_

#define ID_VAR_DUPLICADO 0
#define ID_PAR_DUPLICADO 1
#define ID_PROC_DUPLICADO 2
#define TIPO_MISMATCH 3
#define TIPO_MISMATCH_VAR 4
#define COMP_CON_BOOL 5
#define OP_TIPOS_DIST 6
#define NO_EXISTE_ID 7
#define COMP_SIN_BOOL 8
#define PROC_INEXISTENTE 9
#define NUM_PARAM_NO_MATCH 10
#define ARRAY_MISMATCH 11
#define ID_NO_ARRAY 12
#define DIMENSIONES_MISMATCH 13
#define OUT_OF_BOUNDS 14

#endif /* ERRORDEFINES_HPP_ */